apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secretdbsa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: serectcdbsa
    kind: SecretStore
  target:
    name: secretsdb
    creationPolicy: Owner
  data:
    - secretKey: secret-db-username
      remoteRef:
        key: db-secret-phong
        property: username
    - secretKey: secret-db-password
      remoteRef:
        key: db-secret-phong
        property: password
    - secretKey: secret-db-name
      remoteRef:
        key: db-secret-phong
        property: dbname
    - secretKey: secret-db-host
      remoteRef:
        key: db-secret-phong
        property: host
    - secretKey: secret-db-port
      remoteRef:
        key: db-secret-phong
        property: port
