apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-react-deployment
  namespace: api-production
  labels:
    app: eks-todo-app
spec:
  selector:
    matchLabels:
      app: eks-todo-app
  template:
    metadata:
      labels:
        app: eks-todo-app
    spec:
      containers:
        - name: todo-react-app-phong-trainee
          image: 492804330065.dkr.ecr.us-west-2.amazonaws.com/todoreactapp
          ports:
            - name: http
              containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          imagePullPolicy: IfNotPresent
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secretsdb  
                  key: secret-db-username
                  optional: false
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretsdb  
                  key: secret-db-password
                  optional: false
            - name: SECRET_PORT
              valueFrom:
                secretKeyRef:
                  name: secretsdb  
                  key: secret-db-port
                  optional: false
            - name: SECRET_NAME
              valueFrom:
                secretKeyRef:
                  name: secretsdb  
                  key: secret-db-name
                  optional: false
            - name: SECRET_HOST
              valueFrom:
                secretKeyRef:
                  name: secretsdb  
                  key: secret-db-host
                  optional: false
      nodeSelector:
        kubernetes.io/os: linux
