apiVersion: apps/v1
kind: Deployment
metadata:
  name: pern-todoapp-deployment
  namespace: todoapp
  labels:
    app: pern-todoapp
spec:
  selector:
    matchLabels:
      app: pern-todoapp
  template:
    metadata:
      labels:
        app: pern-todoapp
    spec:
      containers:
        - name: pern-todoapp
          image: <your-images-repo-url>/<your-image-name>:<your-image-tag>
          envFrom:
            - secretRef:
                name: todoapp-secrets 
          ports:
            - name: http
              containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
