apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pern-todoapp-hpa
  namespace: todoapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: pern-todoapp-deployment
 minReplicas: 5
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50