apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alb-certificate-https
  namespace: api-production
spec:
  secretName: alb-certificate-secret
  duration: 2160h 
  renewBefore: 360h 
  commonName: devops-training.opswat.com 
  dnsNames:
    - devops-training.opswat.com
    - be-phong-api.devops-training.opswat.com  
  issuerRef:
    name: letsencrypt-route53 
    kind: ClusterIssuer 
