  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-route53
  spec:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: phonginreallife@gmail.com
      privateKeySecretRef:
        name: letsencrypt-route53-key
      solvers:
        - dns01:
            route53:
              region: us-west-2
              accessKeyID: AKIAXFPLNKJIZLDAERIW
              secretAccessKeySecretRef:
                name: route53-credentials-wind
                key: NNV65cjp/sFaAgbYgbrI27oMt9QxQsMxq/RoCo0l
