apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
  namespace: todoapp
type: Opaque
data:
  SECRET_USERNAME: cG9zdGdyZXM=  
  SECRET_PASSWORD: T0NFc3ZhYnRzVXM4eGtSbw== 
  SECRET_NAME: cGVybnRvZG8=  
  SECRET_HOST: cGVybnRvZG8uY2xrd2c1a3lvMWQ3LnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  CORS_ORIGIN: aHR0cDovL3RmLXBob25nLWZlMjAyNTA0MjUwNzUwMzAxMTg1MDAwMDAwMDEuczMtd2Vic2l0ZS51cy1lYXN0LTIuYW1hem9uYXdzLmNvbQ==