apiVersion: v1
kind: Service
metadata:
  name:  eks-react-phong-trainee-service
  namespace: api-production
  labels:
    app: eks-todo-app
spec:
  selector:
    app: eks-todo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000