# templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.targetName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.dbhub.dbusername }}
      remoteRef:
        key: {{ .Values.secretKeyName }}
        property: username
    - secretKey: {{ .Values.dbhub.dbpass }}
      remoteRef:
        key: {{ .Values.secretKeyName }}
        property: password
    - secretKey: {{ .Values.dbhub.dbname }}
      remoteRef:
        key: {{ .Values.secretKeyName }}
        property: dbname
    - secretKey: {{ .Values.dbhub.dbhost }}
      remoteRef:
        key: {{ .Values.secretKeyName }}
        property: host
    - secretKey: {{ .Values.dbhub.dbport }}
      remoteRef:
        key: {{ .Values.secretKeyName }}
        property: port
